tunga-io/tunga-api

tunga_auth/models.py
tunga_auth/serializers.py
tunga_payments/tests.py
tunga_profiles/models.py
tunga_profiles/serializers.py
tunga_profiles/tests.py
tunga_tasks/tests.py
tunga_utils/constants.py
tunga_utils/serializers.py

```
[ ] Bugfix
[x] Feature
```
No existing way to verify expertise in profiles.
Issue Number(s): [#418](https://github.com/tunga-io/tunga-web/issues/418)
Profile badges based on project completion. Below are the possible badges:
```
1. Tunga talent badge
2. Tunga veteran badge
3. Tunga guru badge
4. Tunga development badge
```
[ ] Yes
[x ] No
Logic: the developer needs to have a Tunga account 
Logic: the developer worked on 0-3 projects or 0-6 months dedicated
Logic: the developer worked on 4-8 projects or 7-18 months dedicated …

Create user profile badges

---

templates/tunga/pdf/base.html
templates/tunga/pdf/credit_note.html
templates/tunga/pdf/invoice.html
templates/tunga/pdf/invoicev3.html

```
[ ] Bugfix
[x] Feature
```
- Outdated invoice design
Issue Number(s): #487
- Updated invoice design to match current designs
```
[ ] Yes
[x] No
```

Update invoice design

---

templates/tunga/pdf/base.html
templates/tunga/pdf/credit_note.html
templates/tunga/pdf/invoicev3.html

```
[x] Bugfix
[ ] Feature
```
- The `HK Grotesk` font is not being set hence design falls to the default `sans serif` font 
- Sets the invoice font to the new design font `HK Grotesk`
```
[ ] Yes
[x] No
```

Set font to HK Grotesk

---

templates/tunga/pdf/base.html

```
[x] Bugfix
```
- Line breaks for long invoice numbers and VAT
- Remove line breaks
```
[x] No
```

Fix invoice line breaks

---

templates/tunga/email/base.html
templates/tunga/email/content.html
templates/tunga/email/new_progress_report.html
templates/tunga/pdf/base.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

updated progress email styles

---

templates/tunga/email/base.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Progress email styles fix

---

templates/tunga/email/base.html
templates/tunga/email/content.html

```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

edit footer link to be white

---

templates/tunga/pdf/base.html
templates/tunga/pdf/invoicev3.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix alignment in pdf

---

tunga_payments/notifications/email.py
tunga_projects/management/commands/tunga_manage_progress_updates.py
tunga_projects/models.py
tunga_projects/tests.py
tunga_projects/utils.py

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Client survey frequency

---

templates/tunga/email/client_survey_reminder_v3.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

change rem to px and loading state of button

---

templates/tunga/html/already_submitted.html
templates/tunga/html/error_submission.html
templates/tunga/html/success_submission.html
templates/tunga/html/survey_confirmation.html

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

Survey interaction email

---

templates/tunga/html/already_submitted.html
templates/tunga/html/error_submission.html
templates/tunga/html/success_submission.html

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

change success message color

---

tunga_projects/views.py

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

reverse devs on survey link

---

templates/tunga/html/survey_confirmation.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

handle link without smiley checked

---

templates/tunga/html/survey_confirmation.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

added error messages for managed projects

---

templates/tunga/html/survey_confirmation.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

checking for uuid instead of pid

---

templates/tunga/html/survey_confirmation.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

undefined id fix

---

templates/tunga/html/survey_confirmation.html

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

change error from developer to project

---

templates/tunga/html/survey_confirmation.html
tunga_projects/views.py

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

check for null developers

---

templates/tunga/html/already_submitted.html
templates/tunga/html/error_submission.html
templates/tunga/html/success_submission.html
templates/tunga/html/survey_confirmation.html

```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

qa ui fixes

---

tunga_utils/management/commands/tunga_export_developers.py

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

added export developers csv

---

tunga_utils/management/commands/tunga_export_user_logins.py

- Modifies fields on csv of export tunga users
```
[ ] Bugfix
[ ] Feature
[x ] Build related changes
```
- The current file does not have a username field on the export
Issue Number(s): 
- https://app.asana.com/0/661985906490017/1199713183890381/f
- The new file will include the username on the exported users
```
[ ] Yes
[ x] No
```

Modify fields on csv of export tunga users

---

tunga_payments/views.py

This PR adds a new endpoint that summarises payments and payout totals
```
[ ] Bugfix
[x] Feature
```
https://app.asana.com/0/661985906490017/1199598408829773/f
```
[ ] Yes
[x] No
```

Add Endpoint For payment-payout Summary

---

tunga_auth/permissions.py
tunga_profiles/models.py
tunga_profiles/sso_helper.py
tunga_profiles/views.py

It allows admins to resend invites to users
```
[x] Bugfix
[ ] Feature
```
Issue Number(s): https://app.asana.com/0/0/1199595749923633/f
```
[ ] Yes
[x] No
```

Fix Invite user for new designs

---

tunga_profiles/views.py

Modifies projects in notifications API to have team members and the latest milestone
```
[ ] Bugfix
[x] Feature
```
Currently, there are no details of the team and a latest milestone on projects in the notifications api.
The notifications api includes details of the team and the latest milestone on projects.
```
[ ] Yes
[x] No
```

Modify notifications api

---

tunga_payments/views.py

Subtracts the total credit_notes value from the paid total on type sale
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

include credit notes in summary
